type Seed = [string, string, string, string, string, string[]?];
const group = (band: string, prefix: string, rows: Seed[]) => rows.map(([id, category, title, prompt, goal, positions]) => ({ id: `${prefix}-${id}`, band, category, title, prompt, goal, positions: positions ?? null }));

// Additional prototype prompts. Original PRD scenarios remain intact.
export const EXTRA_SCENARIOS = [
  ...group('14–17', 'teen', [
    ['interview-mistake', 'career', 'Own a small mistake', 'At your weekend job, you gave a customer the wrong order. Tell your supervisor what happened and what you will do next.', 'Take responsibility and offer a practical correction.'],
    ['volunteer', 'career', 'Find your first volunteer role', 'Introduce yourself to a community center and ask whether you could help with its Saturday events.', 'Explain your interest, availability and how you could contribute.'],
    ['career-question', 'career', 'Ask a speaker a useful question', 'A professional is visiting your class. Ask a question that helps you understand what their job is really like.', 'Ask something specific and leave room for a thoughtful answer.'],
    ['borrowed-headphones', 'conflict', 'Your headphones came back broken', 'A friend returns your borrowed headphones with one side no longer working. Start the conversation without accusing them.', 'Explain what you noticed and agree on a fair next step.'],
    ['lab-credit', 'conflict', 'Share the credit fairly', 'Your lab partner tells the teacher they did most of the experiment, but you split the work evenly. Address it calmly.', 'Clarify the facts and ask for fair recognition.'],
    ['trip-budget', 'money', 'An expensive day out', 'Your friends plan a day out that costs more than you can afford. Suggest an alternative without revealing more than you want to.', 'State a budget boundary and offer an inclusive option.'],
    ['club-budget', 'money', 'One club budget, two ideas', 'Your club has $200 left. Debate buying equipment everyone can use versus spending it on one end-of-year outing.', 'Make a case for your assigned option and acknowledge the trade-off.', ['Buy shared equipment.', 'Fund the end-of-year outing.']],
    ['cancelled-event', 'leadership', 'The venue fell through', 'Your club event is tomorrow and the room booking was cancelled. Explain the situation to your team and propose a backup.', 'Stay calm, set priorities and assign clear next steps.'],
    ['quiet-teammate', 'leadership', 'Make room for a quiet teammate', 'One person has not spoken during a club planning meeting. Invite their ideas without putting them under pressure.', 'Create an easy, respectful way to contribute.'],
    ['say-no', 'social', 'Say no without an excuse', 'A friend wants you to join an activity you do not enjoy. Decline kindly without inventing an excuse.', 'Be clear, warm and honest.'],
    ['group-invite', 'social', 'Someone was left out', 'Your group is arranging a birthday outing, and you notice one friend was accidentally left out of the chat. Bring it up.', 'Include the person without blaming the group.'],
    ['apology', 'social', 'A joke did not land', 'A joke you made upset a friend. Apologize without saying they are too sensitive.', 'Own the impact and explain how you will handle it differently.'],
  ]),
  ...group('18–22', 'student', [
    ['unclear-brief', 'career', 'An unclear internship brief', 'Your supervisor asks you to research competitors but gives no deadline or expected format. Ask for what you need to get started.', 'Clarify the outcome, deadline and priorities concisely.'],
    ['network-followup', 'career', 'Follow up after a great conversation', 'You met an alumnus at a networking event yesterday. Send a short follow-up asking for a 15-minute career conversation.', 'Refer to the conversation and make a specific, low-pressure request.'],
    ['intern-feedback', 'career', 'Your mid-internship check-in', 'Halfway through your internship, ask your supervisor what you should keep doing and what you could improve.', 'Seek specific feedback and a useful action for the next week.'],
    ['chat-tone', 'conflict', 'The group chat got tense', 'A teammate reads your short project message as rude. Clear up the misunderstanding without arguing about their reaction.', 'Acknowledge the impact, explain your intent and reset the conversation.'],
    ['idea-credit', 'conflict', 'A teammate presents your idea', 'During a presentation, a teammate describes your proposal as their own. Speak with them afterward.', 'Explain your concern and agree on how contributions will be credited.'],
    ['travel-budget', 'money', 'Different budgets, one trip', 'Your friends want a graduation trip, but everyone has a different budget. Propose a way to plan fairly.', 'Ask about limits and compare practical alternatives without pressure.'],
    ['dinner-bill', 'money', 'The dinner bill is uneven', 'At a group dinner, some friends ordered much more than others. Suggest how to split the bill.', 'Make a clear, fair proposal and acknowledge different preferences.'],
    ['event-format', 'leadership', 'Online event or in-person meetup?', 'Your student society can host its next networking event online or in person. Debate which format to choose.', 'Defend your assigned format while considering access and engagement.', ['Host the event online.', 'Host the event in person.']],
    ['low-turnout', 'leadership', 'Your event barely filled a room', 'Only six people attended an event your team worked hard on. Lead the debrief without blaming anyone.', 'Recognize the effort and choose one improvement based on evidence.'],
    ['team-priorities', 'leadership', 'Three tasks, one afternoon', 'Your project team has one afternoon to fix three issues before a presentation. Explain how you would choose what comes first.', 'Use clear criteria and assign manageable responsibilities.'],
    ['friend-rejection', 'social', 'Support a disappointed friend', 'Your friend was rejected from an internship they really wanted. Start a supportive conversation without offering instant solutions.', 'Listen, acknowledge their disappointment and ask what support they want.'],
    ['favor-boundary', 'social', 'You cannot always proofread', 'A friend keeps asking you to review assignments at the last minute. Set a boundary while showing you care.', 'State what you can realistically offer and suggest more notice.'],
  ]),
  ...group('23+', 'adult', [
    ['career-pivot', 'career', 'Explain a career pivot', 'An interviewer asks why you are moving from customer support into project coordination. Explain the connection.', 'Link transferable skills to the new role with one example.'],
    ['scope-request', 'career', 'The project keeps getting bigger', 'A stakeholder asks for extra work two days before delivery. Discuss the impact and propose options.', 'Make the trade-offs clear without promising an impossible deadline.'],
    ['mentor-request', 'career', 'Ask someone to mentor you', 'Ask an experienced colleague whether they would be open to a short monthly conversation about your professional growth.', 'Explain your goal and respect their time and ability to decline.'],
    ['workload', 'conflict', 'Everything is urgent', 'Two managers each say their task is your top priority today. Ask them to help agree on an order.', 'Present the conflict neutrally and request a clear decision.'],
    ['interruptions', 'conflict', 'Finish your thought', 'A colleague regularly interrupts you in meetings. Address it respectfully after the meeting.', 'Describe the pattern and make a specific request.'],
    ['trip-cost', 'money', 'A shared holiday costs more', 'The accommodation your friends chose is beyond your budget. Suggest a different plan before anyone books.', 'Be direct about your limit and offer a workable alternative.'],
    ['invoice', 'money', 'A client asks for a discount', 'A freelance client asks for a 25% discount on an agreed project price. Respond while protecting the working relationship.', 'Explain the value and discuss scope or timing alternatives.'],
    ['hybrid-team', 'leadership', 'Choose the team’s meeting format', 'Your distributed team must choose between remote planning meetings and a monthly in-person planning day. Debate the options.', 'Argue your assigned position while considering participation and coordination.', ['Keep planning meetings remote.', 'Hold a monthly in-person planning day.']],
    ['failed-launch', 'leadership', 'A launch missed its target', 'Your team launched a feature and adoption was lower than expected. Open a review meeting.', 'Create space for honest learning and propose a focused next experiment.'],
    ['delegate', 'leadership', 'Delegate without micromanaging', 'You need a teammate to lead a client update you normally handle. Explain the task and the support you can offer.', 'Define the outcome, ownership and check-in points.'],
    ['unwanted-advice', 'social', 'The advice is getting tiring', 'A friend keeps giving unsolicited advice about your career. Tell them what kind of support would help more.', 'Set a kind boundary and explain what you need.'],
    ['missed-milestone', 'social', 'You missed an important day', 'You forgot a close friend’s important milestone. Reach out and apologize without making excuses.', 'Acknowledge the hurt and offer a thoughtful way to reconnect.'],
  ]),
];

EXTRA_SCENARIOS.push(
  ...group('14–17','teen-plus',[
    ['first-interview','career','Tell me about yourself','A library manager asks you to introduce yourself for a weekend assistant role. You have no paid work experience yet.','Connect a school or volunteering example to what the role needs.'],
    ['feedback-interview','career','Describe feedback you used','An interviewer asks about a time you received feedback on your work. Describe the change you made.','Give a concrete before-and-after example without inventing experience.'],
    ['availability','career','Explain your availability','A shop asks you to work on an evening when you have a regular school commitment. Respond during the interview.','Be honest about your limit and offer a workable alternative.'],
    ['interruptions','conflict','Finish your point','A classmate repeatedly talks over you during a group presentation rehearsal. Ask for space to finish.','Describe the behavior and suggest a fair turn-taking rule.'],
    ['group-chat','conflict','A joke went too far','A friend posts a joke about you in a group chat and you do not find it funny. Explain your boundary.','State the impact and what you want to happen next.'],
    ['practice-space','conflict','Share a practice space','Two school clubs both need the same room before an event. Propose a solution to the other organizer.','Acknowledge both needs and offer a specific schedule.'],
    ['fundraiser','money','Choose a fundraiser','Your club must choose between a low-cost bake sale and a ticketed performance requiring more planning.','Compare effort, accessibility and uncertainty.', ['Choose the bake sale.','Choose the ticketed performance.']],
    ['borrow-money','money','Decline a loan kindly','A friend asks to borrow money you have saved for something important. You cannot afford to lend it.','Say no clearly without judging your friend or making a false promise.'],
    ['new-member','leadership','Welcome a new member','A new club member looks unsure how to join the activity. Introduce yourself and help them take part.','Explain the activity, ask what they enjoy and offer a small first step.'],
    ['missed-task','leadership','Recover a missed task','Your event team forgot to arrange signs and the event starts tomorrow. Lead a short planning conversation.','Prioritize the essential work and assign clear ownership.'],
    ['different-interest','social','Suggest a different activity','Your friends always choose a game you do not enjoy. Ask to try something different next time.','Express your preference and make room for theirs.'],
    ['new-class','social','Start a conversation','You sit beside someone new in class and want to start a friendly conversation before the lesson.','Use a shared context and an easy question without pressuring them.'],
  ]),
  ...group('18–22','student-plus',[
    ['interview-intro','career','A 60-second interview introduction','A recruiter asks you to introduce yourself for an internship. Connect your interests with one relevant project.','Choose one clear theme and support it with a real example.'],
    ['interview-failure','career','Explain a setback','An interviewer asks about a project that did not go as planned. Explain your role and what you changed.','Own your contribution, describe the lesson and avoid blaming teammates.'],
    ['interview-question','career','Ask the interviewer a question','Your internship interview is ending. Ask a question that helps you understand the team and role.','Show curiosity about specific responsibilities, support or success criteria.'],
    ['roommate-guest','conflict','Unexpected overnight guests','Your roommate often invites overnight guests without checking with you. Start a conversation about shared space.','Name the impact and propose a mutual agreement.'],
    ['project-edit','conflict','Your work was changed','A teammate rewrote your section shortly before a group submission without discussing it. Address it after the deadline.','Ask about their reasoning and agree on how to handle future edits.'],
    ['internship-task','conflict','An unclear assignment','Your supervisor gives conflicting instructions and your deadline is close. Ask for clarity.','Summarize the conflict and ask which outcome has priority.'],
    ['salary-question','money','An internship pay question','A recruiter asks about your pay expectations before explaining the role’s budget. Respond professionally.','Ask for the range and discuss responsibilities without inventing market data.'],
    ['shared-expense','money','Split a shared expense','Your group ordered food together but one person’s meal cost much more. Suggest a fair way to divide the bill.','Explain a practical option without embarrassing anyone.'],
    ['quiet-team','leadership','Invite quieter voices','Two people dominate your project discussion while others have not spoken. Help the group hear more perspectives.','Make participation easier without putting someone on the spot.'],
    ['project-scope','leadership','Reduce an overlarge project','Your team wants to build five features but has time for two. Facilitate a decision.','Agree on the goal and choose a small, testable first version.'],
    ['network-followup','social','Follow up after meeting someone','You met a student from another course who mentioned a shared interest. Start an in-person follow-up conversation.','Refer to the shared topic and suggest a low-pressure next interaction.'],
    ['friend-distance','social','A friendship feels distant','A friend has been less available lately. Check in without assuming they are avoiding you.','Express care, ask an open question and respect their space.'],
  ]),
  ...group('23+','adult-plus',[
    ['career-change','career','Explain a career change','An interviewer asks why you are moving into a different type of role. Explain the connection to your previous experience.','Show transferable skills and a realistic reason for the change.'],
    ['interview-disagree','career','Disagree with a manager','An interviewer asks about a time you disagreed with a manager. Explain how you handled it.','Focus on evidence, respectful discussion and the outcome.'],
    ['interview-gap','career','Discuss time away from work','An interviewer asks about a break in your work history. Share only what you are comfortable sharing and return to your readiness for the role.','Set a personal boundary while addressing the role’s requirements.'],
    ['urgent-message','conflict','After-hours urgency','A colleague regularly labels non-urgent evening messages as urgent. Discuss a better way to communicate.','Agree on what urgent means and a reasonable response expectation.'],
    ['client-boundary','conflict','A client changes the brief','A client wants substantial extra work before an unchanged deadline. Respond with options.','Clarify the change and explain trade-offs without making threats.'],
    ['meeting-credit','conflict','Correct a misunderstanding','In a meeting, someone attributes your analysis to another team. Correct the record constructively.','State the contribution clearly while keeping the discussion productive.'],
    ['renewal-price','money','Negotiate a service renewal','A supplier proposes a higher renewal price. You have a limited budget and want to discuss options.','Ask what changed and explore scope, term or service alternatives.'],
    ['training-budget','money','Make a training case','You want your manager to approve a training course using a limited team budget. Make your case.','Connect the training to a practical team need and acknowledge the cost.'],
    ['change-process','leadership','Introduce a new process','Your team is frustrated by another proposed workflow change. Explain why you want to try it.','Acknowledge the disruption and propose a limited pilot with feedback.'],
    ['handoff-risk','leadership','Flag a handoff risk','A project handoff is approaching but a critical decision has no owner. Raise the issue in a planning meeting.','Make the risk concrete and ask for a named owner and deadline.'],
    ['decline-invite','social','Decline without overexplaining','A friend invites you to a weekend trip you do not want to take. Respond kindly and directly.','Avoid a false excuse and offer another way to connect if you want to.'],
    ['repair-comment','social','Repair an awkward comment','You realize a comment you made in a conversation landed badly. Follow up with the person.','Acknowledge the comment and its impact without demanding reassurance.'],
  ]),
);
