import type { AgeBand, PracticeLog } from '../../shared/pitch'

const samples = [
  {title:'Tell me about yourself',category:'career',prompt:'Introduce yourself to an internship interviewer.',response:'I study design and enjoy turning research into simple products. In our last team project, I interviewed six students and used their feedback to improve the sign-up flow. I would love to bring that mix of curiosity and practical design to your team.',strength:'“I interviewed six students” gives a concrete example.',improve:'Connect the project outcome to the role you want.',example:'I want to bring my user research and design experience to your internship.'},
  {title:'Ask for a deadline change',category:'conflict',prompt:'Ask a teammate to move a deadline while keeping the project on track.',response:'I want to flag a delay before it affects the team. The survey results arrived late, so I need one extra day to finish the analysis. I can send the first findings today and the complete version tomorrow afternoon. Would that still work for your presentation?',strength:'You offered “the first findings today” as a useful compromise.',improve:'Name the exact time for the final handoff.',example:'I can send the final analysis by 3 pm tomorrow. Does that fit your timeline?'},
  {title:'Negotiate a starting salary',category:'money',prompt:'Ask whether a job offer has room for a higher starting salary.',response:'Thank you for the offer. I am excited about the team and the work. Based on the responsibilities and my relevant project experience, is there flexibility in the starting salary? I would also be happy to discuss training support if the salary range is fixed.',strength:'You opened with appreciation and kept the request clear.',improve:'Support your request with one specific relevant achievement.',example:'My project experience matches these responsibilities. Could we discuss the salary range?'},
  {title:'Lead a team check-in',category:'leadership',prompt:'Help your team agree on the next steps for a shared project.',response:'Before we split up, let us agree on the three tasks that matter this week. I can handle the research summary, and we still need owners for the slides and the prototype. What is everyone comfortable taking on, and what support would help?',strength:'“What support would help?” invites teammates to raise concerns.',improve:'Add a clear time to check progress together.',example:'Let us check in on Thursday afternoon so we can fix any blockers early.'},
]
export function demoPracticeLogs(band:AgeBand,now=Date.now()):PracticeLog[] {
  return samples.map((s,i)=>({id:`demo-practice-${i}`,scenarioId:`demo-practice-${i}`,scenario:{id:`demo-practice-${i}`,band,title:s.title,category:s.category,prompt:s.prompt,goal:'Practice a clear response.',positions:null},transcript:s.response,feedback:`What worked: ${s.strength}\nTry next: ${s.improve}\nExample: ${s.example}`,delivery:{seconds:42+i*4,samples:420+i*40,audiblePercent:72+i,pauses:2,levelRangeDb:8},createdAt:now-i*86400000,updatedAt:now-i*86400000}))
}
